import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // PANTALLA DE SELECCIÓN
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  safeArea: {
    flex: 1,
  },
  selectionScreen: {
    flex: 1,
    justifyContent: 'center',
    paddingVertical: 20,
  },
  title: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FFD700',
    textAlign: 'center',
    marginBottom: 30,
    textShadowColor: '#FF0000',
    textShadowOffset: { width: 4, height: 4 },
    textShadowRadius: 0,
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  teamsContainer: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 15,
    gap: 10,
  },
  teamSection: {
    flex: 1,
    borderWidth: 5,
    borderRadius: 0,
    padding: 12,
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.8,
    shadowRadius: 0,
  },
  teamSectionHome: {
    borderColor: '#FFD700',
    backgroundColor: '#1a1a2e',
    shadowColor: '#FFD700',
  },
  teamSectionAway: {
    borderColor: '#00FF00',
    backgroundColor: '#1a1a2e',
    shadowColor: '#00FF00',
  },
  teamLabel: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 2,
    textTransform: 'uppercase',
    paddingVertical: 5,
    borderBottomWidth: 3,
  },
  teamLabelHome: {
    color: '#FFD700',
    borderBottomColor: '#FFD700',
  },
  teamLabelAway: {
    color: '#00FF00',
    borderBottomColor: '#00FF00',
  },
  logoContainer: {
    alignItems: 'center',
    marginVertical: 8,
    paddingVertical: 10,
    backgroundColor: '#0a0a0a',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#333',
  },
  logo: {
    fontSize: 50,
    marginBottom: 8,
  },
  logoImage: {
    width: 70,
    height: 70,
    marginBottom: 8,
  },
  teamName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 3,
    letterSpacing: 1,
  },
  changeButton: {
    backgroundColor: '#FF00FF',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 0,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    marginVertical: 8,
    shadowColor: '#FF00FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 0,
  },
  changeButtonText: {
    color: '#000000',
    textAlign: 'center',
    fontSize: 13,
    fontWeight: 'bold',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
  playersTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#00FFFF',
    marginTop: 8,
    marginBottom: 5,
    textAlign: 'center',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  playersList: {
    maxHeight: 140,
  },
  playerItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
    paddingHorizontal: 6,
    backgroundColor: '#16213e',
    marginVertical: 2,
    borderRadius: 0,
    borderLeftWidth: 3,
    borderLeftColor: '#00FFFF',
  },
  playerName: {
    color: '#FFFFFF',
    fontSize: 10,
    flex: 1,
  },
  playerNumber: {
    color: '#FFD700',
    fontSize: 10,
    fontWeight: 'bold',
    marginLeft: 5,
  },
  startButton: {
    backgroundColor: '#FF0000',
    paddingVertical: 18,
    marginHorizontal: 40,
    marginTop: 25,
    borderRadius: 0,
    borderWidth: 5,
    borderColor: '#FFD700',
    shadowColor: '#FF0000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.8,
    shadowRadius: 0,
  },
  startButtonText: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 26,
    fontWeight: 'bold',
    letterSpacing: 4,
    textShadowColor: '#000000',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 0,
    textTransform: 'uppercase',
  },

  // PANTALLA DE MATCH (JUEGO)
  matchScreen: {
    flex: 1,
    paddingVertical: 20,
  },
  matchTitle: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#FF00FF',
    textAlign: 'center',
    marginBottom: 15,
    textShadowColor: '#00FFFF',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 0,
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  matchScoreboard: {
    backgroundColor: '#1a1a2e',
    borderWidth: 6,
    borderColor: '#FFD700',
    
    padding: 10,
    borderRadius: 0,
    marginBottom: 20,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.8,
    shadowRadius: 0,
  },
  matchScoreRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  matchTeamInfo: {
    alignItems: 'center',
    width: 70,
  },
  matchTeamLogo: {
    fontSize: 32,
  },
  matchTeamLogoImage: {
    width: 45,
    height: 45,
  },
  matchTeamName: {
    color: '#FFFFFF',
    fontSize: 9,
    fontWeight: 'bold',
    marginTop: 3,
    textAlign: 'center',
  },
  matchScoreBox: {
    backgroundColor: '#000000',
    paddingVertical: 8,
    borderRadius: 0,
    borderWidth: 4,
    borderColor: '#FF0000',
    width: 75,
  },
  matchScore: {
    fontSize: 34,
    fontWeight: 'bold',
    color: '#FFD700',
    textAlign: 'center',
    textShadowColor: '#FF0000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 0,
  },
  matchVsText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#00FFFF',
    textAlign: 'center',
    width: 35,
  },
  playersContainer: {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 15,
    gap: 10,
  },
  playerColumn: {
    flex: 1,
  },
  playerColumnTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    letterSpacing: 2,
    textTransform: 'uppercase',
    paddingVertical: 5,
  },
  playerColumnTitleHome: {
    color: '#FFD700',
  },
  playerColumnTitleAway: {
    color: '#00FF00',
  },
  matchPlayerItem: {
    backgroundColor: '#16213e',
    padding: 8,
    marginVertical: 4,
    borderLeftWidth: 4,
    borderRadius: 0,
  },
  matchPlayerItemHome: {
    borderLeftColor: '#FFD700',
  },
  matchPlayerItemAway: {
    borderLeftColor: '#00FF00',
  },
  matchPlayerInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  matchPlayerName: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: 'bold',
    flex: 1,
  },
  matchPlayerNumber: {
    color: '#00FFFF',
    fontSize: 11,
    fontWeight: 'bold',
  },
  matchPlayerButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    gap: 5,
  },
  scoreButton: {
    flex: 1,
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 0,
    borderWidth: 2,
    alignItems: 'center',
  },
  scoreButton2: {
    backgroundColor: '#FF6600',
    borderColor: '#FFD700',
  },
  scoreButton3: {
    backgroundColor: '#9900FF',
    borderColor: '#00FF00',
  },
  scoreButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  endGameButton: {
    backgroundColor: '#FF0000',
    paddingVertical: 15,
    marginHorizontal: 40,
    marginTop: 15,
    borderRadius: 0,
    borderWidth: 5,
    borderColor: '#FFD700',
    shadowColor: '#FF0000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.8,
    shadowRadius: 0,
  },
  endGameButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 3,
    textTransform: 'uppercase',
  },

  // PANTALLA DE GANADOR
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 10,
    backgroundColor: '#FF0000',
    width: 50,
    height: 50,
    borderRadius: 0,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    color: '#FFFFFF',
    fontSize: 30,
    fontWeight: 'bold',
  },
  winnerScrollContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 80,
    paddingBottom: 30,
    alignItems: 'center',
  },
  winnerContainer: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#1a1a2e',
    padding: 30,
    borderRadius: 0,
    borderWidth: 8,
    borderColor: '#FFD700',
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 0,
    marginBottom: 20,
  },
  winnerTitle: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#FFD700',
    marginBottom: 30,
    textShadowColor: '#FF0000',
    textShadowOffset: { width: 4, height: 4 },
    textShadowRadius: 0,
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  winnerLogo: {
    fontSize: 100,
    marginBottom: 20,
  },
  winnerLogoImage: {
    width: 140,
    height: 140,
    marginBottom: 20,
  },
  winnerTeamName: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 20,
    letterSpacing: 2,
  },
  winnerScore: {
    fontSize: 50,
    fontWeight: 'bold',
    color: '#00FF00',
    textShadowColor: '#000000',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 0,
  },
  tieTitle: {
    fontSize: 40,
    fontWeight: 'bold',
    color: '#FF00FF',
    marginBottom: 30,
    textShadowColor: '#00FFFF',
    textShadowOffset: { width: 4, height: 4 },
    textShadowRadius: 0,
    letterSpacing: 3,
    textTransform: 'uppercase',
  },
  tieLogosContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginBottom: 20,
  },
  tieLogo: {
    fontSize: 80,
  },
  tieLogoImage: {
    width: 100,
    height: 100,
  },
  tieTeamName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 10,
  },
  tieScore: {
    fontSize: 50,
    fontWeight: 'bold',
    color: '#FFD700',
    textAlign: 'center',
    textShadowColor: '#000000',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 0,
  },
  newGameButton: {
    backgroundColor: '#00FF00',
    paddingVertical: 15,
    paddingHorizontal: 40,
    marginTop: 30,
    borderRadius: 0,
    borderWidth: 5,
    borderColor: '#000000',
    shadowColor: '#00FF00',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.8,
    shadowRadius: 0,
  },
  newGameButtonText: {
    color: '#000000',
    fontSize: 20,
    fontWeight: 'bold',
    letterSpacing: 3,
    textTransform: 'uppercase',
  },

matchPlayerPoints: {
  color: '#FFD700',
  fontSize: 10,
  fontWeight: 'bold',
  marginBottom: 6,
},

top5Container: {
  width: '100%',
  backgroundColor: '#1a1a2e',
  padding: 20,
  borderRadius: 0,
  borderWidth: 5,
  borderColor: '#00FFFF',
  marginBottom: 20,
  
},
top5Title: {
  fontSize: 24,
  fontWeight: 'bold',
  color: '#FFD700',
  textAlign: 'center',
  marginBottom: 20,
  textTransform: 'uppercase',
  letterSpacing: 2,
},
top5Item: {
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: '#16213e',
  padding: 12,
  marginVertical: 5,
  borderLeftWidth: 5,
  borderLeftColor: '#FFD700',
},
top5Position: {
  fontSize: 18,
  fontWeight: 'bold',
  color: '#FFD700',
  width: 40,
},
top5Info: {
  flex: 1,
},
top5Name: {
  fontSize: 16,
  fontWeight: 'bold',
  color: '#FFFFFF',
},
top5Points: {
  fontSize: 20,
  fontWeight: 'bold',
  color: '#00FF00',
},

backButtonTopText: {
  color: '#FFFFFF',
  fontSize: 16,
  fontWeight: 'bold',
  letterSpacing: 2,
}});